name: ScavengerHunt
version: 1.1
main: user.puntoofa.scavengerHunt.ScavengerHunt
api-version: '1.21'
load: STARTUP
authors: [ The_Great_K ]
description: "Scavenger hunt plugin made for Puntoofa"

commands:
  sstart:
    description: "Starts scavenger hunt, /scav is enabled, /additem is disabled"
    usage: "/sstart"
    permission: scavengerhunt.commands.start
    permission-message: "You do not have permission to use this command!"
  spause:
    description: "Pauses scavenger hunt, /scav is disabled, /additem is enabled"
    usage: "/spause"
    permission: scavengerhunt.commands.pause
    permission-message: "You do not have permission to use this command!"
  srestart:
    description: "Restarts scavenger hunt, /scav is disabled, /additem is enabled, progress and gui is reset"
    usage: "/srestart"
    permission: scavengerhunt.commands.restart
    permission-message: "You do not have permission to use this command!"
  scav:
    description: "Opens scavenger hunt gui of items that need to be found"
    usage: "/scav"
    permission: scavengerhunt.commands.gui
    permission-message: "You do not have permission to use this command!"
  additem:
    description: "Adds held/specified item to scavenger list in specified slot"
    usage: "/additem <slot> [<item>]"
    permission: scavengerhunt.commands.add
    permission-message: "You do not have permission to use this command!"
  removeitem:
    description: "Removes item in specified slot from scavenger list"
    usage: "/removeitem <slot>"
    permission: scavengerhunt.commands.remove
    permission-message: "You do not have permission to use this command!"

permissions:
  scavengerhunt.commands.start:
    description: "Starts scavenger hunt"
    permission: op
  scavengerhunt.commands.pause:
    description: "Pauses scavenger hunt"
    permission: op
  scavengerhunt.commands.restart:
    description: "Restarts scavenger hunt"
    permission: op
  scavengerhunt.commands.gui:
    description: "Opens main scavenger gui"
    default: true
  scavengerhunt.commands.add:
    description: "Adds scavenger item to list"
    default: op
  scavengerhunt.commands.remove:
    description: "Removes scavenger item from list"
    default: op